# Site settings
author: Robyn
title: Journey Through Flatiron
header-img: img/home-bg.png
email: rhtaylor0715@gmail.com
copyright_name: Robyn
description: > # this means to ignore newlines until "baseurl:"
  Self-Paced Software Engineering Course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rh-taylor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
